# For the estimation of E[Y|W, T]
[Qcont]
    # Description of the outcome
    [Qcont.outcome]
    type = "continuous"
    # Description of the resampling strategy
    [Qcont.resampling]
    type = "CV"
    nfolds = 2
    # List all models and hyperparameters
    [Qcont.LinearRegressor]
    fit_intercept = true

# For the estimation of E[Y|W, T]
[Qcat]
    # Description of the outcome
    [Qcat.outcome]
    type = "binary"

    # Description of the resampling strategy
    [Qcat.resampling]
    type = "StratifiedCV"
    nfolds = 2
    # List all models and hyperparameters
    [Qcat.LogisticClassifier]
    fit_intercept = true

# For the estimation of p(T| W)
[G]
    # Description of the outcome
    [G.outcome]
    type = "categorical"
    # Description of the resampling strategy
    [G.resampling]
    type = "StratifiedCV"
    nfolds = 2
    # List all models and hyperparameters
    [G.LogisticClassifier]
    fit_intercept = true



