# Sample variants with probability over this threshold will be called
# Others will be declared as missing
threshold = 0.9

# List of potentially interacting variants and a path to their respective chromosome file
[SNPS]

RSID_1 = "PATH TO CHROMOSOME"
RSID_2 = "PATH TO CHROMOSOME"

# List of queries (the query names are not important)
# A query is the specification of a "control" and "treatment" genotype 
# for each variant.
[QUERY_1]

RSID_1 = "AA -> AT"
RSID_2 = "AA -> TT"

[QUERY_2]

RSID_1 = "TT -> AA"
RSID_2 = "AA -> TT"