name: "Test read file version"

on:
  workflow_dispatch

jobs:
  file_contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set Version
        run:  echo "PKG_VERSION=$(grep version Project.toml | cut -d '"' -f2)" >> $GITHUB_ENV

      - name: File contents
        run: echo "olivierlabayle/tmle-epistasis:${{ env.PKG_VERSION }}"
