name: "Test read file version"

on:
  workflow_dispatch

jobs:
  file_contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Read file contents
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: "Project.toml"

      - name: File contents
        run: echo "${ steps.read_file.outputs.contents }"
